server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      # Hacemos que el Gateway busque los servicios dinámicamente en Eureka usando sus nombres
      #discovery:
        #locator:
          #enabled: true
          #lower-case-service-id: true # Convierte los nombres de MS a minúsculas en la URL

      routes:
        - id: persona
          uri: lb://PERSONA
          predicates:
            - Path=/persona/**

        - id: pago
          uri: lb://PAGO
          predicates:
            - Path=/pago/**

        - id: empresa
          uri: lb://EMPRESA
          predicates:
            - Path=/empresa/**
          filters:
            - StripPrefix=1

        - id: direccion
          uri: lb://DIRECCION
          predicates:
            - Path=/direccion/**

        - id: despacho
          uri: lb://DESPACHO
          predicates:
            - Path=/despacho/**

        - id: conductor
          uri: lb://CONDUCTOR
          predicates:
            - Path=/conductor/**

        - id: camion
          uri: lb://CAMION
          predicates:
            - Path=/camion/**

# Conectamos el Gateway a Eureka para que sepa mapear las rutas
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/