spring:
  application:
    name: persona

  datasource:
    url: jdbc:mysql://localhost:3306/persona_db
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
  swagger-ui:
    enabled: true